// <auto-generated />
using System;
using Cashere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cashere.Data.Migrations
{
    [DbContext(typeof(CashereDbContext))]
    partial class CashereDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Cashere.Models.Cashier", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Cashiers");
            });

            modelBuilder.Entity("Cashere.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Categories");
            });

            modelBuilder.Entity("Cashere.Models.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Address")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasColumnType("TEXT");

                b.Property<string>("Phone")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("Cashere.Models.InventoryMovement", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("MovementType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasColumnType("TEXT");

                b.Property<int>("ProductId")
                    .HasColumnType("INTEGER");

                b.Property<int>("QuantityChange")
                    .HasColumnType("INTEGER");

                b.Property<int?>("ReferenceId")
                    .HasColumnType("INTEGER");

                b.Property<string>("ReferenceType")
                    .HasMaxLength(30)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CreatedAt");

                b.HasIndex("ProductId");

                b.ToTable("InventoryMovements");
            });

            modelBuilder.Entity("Cashere.Models.Payment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<string>("Method")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("PaidAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ReferenceNumber")
                    .HasColumnType("TEXT");

                b.Property<int>("SaleId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("SaleId");

                b.ToTable("Payments");
            });

            modelBuilder.Entity("Cashere.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Barcode")
                    .HasColumnType("TEXT");

                b.Property<int?>("CategoryId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("CostPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<int>("LowStockThreshold")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("PhotoPath")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<decimal>("SellingPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<string>("Sku")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<int>("StockQuantity")
                    .HasColumnType("INTEGER");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Barcode")
                    .IsUnique()
                    .HasFilter("Barcode IS NOT NULL");

                b.HasIndex("CategoryId");

                b.HasIndex("Sku")
                    .IsUnique();

                b.ToTable("Products");
            });

            modelBuilder.Entity("Cashere.Models.Purchase", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("CreatedByCashierId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Notes")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("PurchaseDate")
                    .HasColumnType("TEXT");

                b.Property<string>("ReferenceNumber")
                    .HasColumnType("TEXT");

                b.Property<int>("SupplierId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("TotalAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CreatedByCashierId");

                b.HasIndex("SupplierId");

                b.ToTable("Purchases");
            });

            modelBuilder.Entity("Cashere.Models.PurchaseItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ProductId")
                    .HasColumnType("INTEGER");

                b.Property<int>("PurchaseId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Subtotal")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<decimal>("UnitCost")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.HasIndex("PurchaseId");

                b.ToTable("PurchaseItems");
            });

            modelBuilder.Entity("Cashere.Models.Sale", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("CashierId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("CustomerId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("DiscountAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("SaleDate")
                    .HasColumnType("TEXT");

                b.Property<string>("SaleNumber")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Subtotal")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<decimal>("TaxAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CashierId");

                b.HasIndex("CustomerId");

                b.HasIndex("SaleDate");

                b.HasIndex("SaleNumber")
                    .IsUnique();

                b.ToTable("Sales");
            });

            modelBuilder.Entity("Cashere.Models.SaleItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ProductId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.Property<int>("SaleId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Subtotal")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<decimal>("UnitCostAtSale")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<decimal>("UnitPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.HasIndex("SaleId");

                b.ToTable("SaleItems");
            });

            modelBuilder.Entity("Cashere.Models.ReceiptAdmin", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Address")
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<string>("Phone")
                    .HasColumnType("TEXT");

                b.Property<string>("ReceiptFooterText")
                    .HasColumnType("TEXT");

                b.Property<string>("ServerBindAddress")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<int>("ServerPort")
                    .HasColumnType("INTEGER");

                b.Property<string>("ShopName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<decimal>("TaxRatePercent")
                    .HasPrecision(5, 2)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("ReceiptAdmin");
            });

            modelBuilder.Entity("Cashere.Models.Supplier", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Address")
                    .HasColumnType("TEXT");

                b.Property<string>("ContactPerson")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasColumnType("TEXT");

                b.Property<string>("Phone")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Suppliers");
            });

            modelBuilder.Entity("Cashere.Models.InventoryMovement", b =>
            {
                b.HasOne("Cashere.Models.Product", "Product")
                    .WithMany("InventoryMovements")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

            modelBuilder.Entity("Cashere.Models.Payment", b =>
            {
                b.HasOne("Cashere.Models.Sale", "Sale")
                    .WithMany("Payments")
                    .HasForeignKey("SaleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Sale");
            });

            modelBuilder.Entity("Cashere.Models.Product", b =>
            {
                b.HasOne("Cashere.Models.Category", "Category")
                    .WithMany("Products")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Category");
            });

            modelBuilder.Entity("Cashere.Models.Purchase", b =>
            {
                b.HasOne("Cashere.Models.Cashier", "CreatedByCashier")
                    .WithMany("Purchases")
                    .HasForeignKey("CreatedByCashierId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Cashere.Models.Supplier", "Supplier")
                    .WithMany("Purchases")
                    .HasForeignKey("SupplierId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("CreatedByCashier");

                b.Navigation("Supplier");
            });

            modelBuilder.Entity("Cashere.Models.PurchaseItem", b =>
            {
                b.HasOne("Cashere.Models.Product", "Product")
                    .WithMany("PurchaseItems")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Cashere.Models.Purchase", "Purchase")
                    .WithMany("Items")
                    .HasForeignKey("PurchaseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");

                b.Navigation("Purchase");
            });

            modelBuilder.Entity("Cashere.Models.Sale", b =>
            {
                b.HasOne("Cashere.Models.Cashier", "Cashier")
                    .WithMany("Sales")
                    .HasForeignKey("CashierId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Cashere.Models.Customer", "Customer")
                    .WithMany("Sales")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Cashier");

                b.Navigation("Customer");
            });

            modelBuilder.Entity("Cashere.Models.SaleItem", b =>
            {
                b.HasOne("Cashere.Models.Product", "Product")
                    .WithMany("SaleItems")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Cashere.Models.Sale", "Sale")
                    .WithMany("Items")
                    .HasForeignKey("SaleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");

                b.Navigation("Sale");
            });

            modelBuilder.Entity("Cashere.Models.Cashier", b =>
            {
                b.Navigation("Purchases");

                b.Navigation("Sales");
            });

            modelBuilder.Entity("Cashere.Models.Category", b =>
            {
                b.Navigation("Products");
            });

            modelBuilder.Entity("Cashere.Models.Customer", b =>
            {
                b.Navigation("Sales");
            });

            modelBuilder.Entity("Cashere.Models.Product", b =>
            {
                b.Navigation("InventoryMovements");

                b.Navigation("PurchaseItems");

                b.Navigation("SaleItems");
            });

            modelBuilder.Entity("Cashere.Models.Purchase", b =>
            {
                b.Navigation("Items");
            });

            modelBuilder.Entity("Cashere.Models.Sale", b =>
            {
                b.Navigation("Items");

                b.Navigation("Payments");
            });

            modelBuilder.Entity("Cashere.Models.Supplier", b =>
            {
                b.Navigation("Purchases");
            });
#pragma warning restore 612, 618
        }
    }
}